#!/bin/bash

VM_NAME=lenaps-vm

startvm() {
    VBoxManage startvm $VM_NAME --type headless
}

setup() {
    VBoxManage modifyvm $VM_NAME --natpf1 "ssh,tcp,,3022,,22"
    startvm
}

enter_ssh() {
    startvm
    ssh -p 3022 ${1}@127.0.0.1
}

# Main
case $1 in
    '')
        enter_ssh pugachag
        ;;
    enter)
        enter_ssh $2
        ;;
    configure)
        setup
        ;;
esac
