#!/bin/bash

VM_NAME=lenaps-vm

startvm() {
    VBoxManage startvm $VM_NAME --type headless
}

forward_port() {
    VBoxManage modifyvm $VM_NAME --natpf1 "nat-port$1,tcp,,$1,,$2"
}

setup() {
    forward_port 3022 22
    for i in {8000..8999}; do
        forward_port $i $i
    done
    startvm
}

start_clip_serv() {
    nohup clip_serv.py >/dev/null 2>&1 &
}

enter_ssh() {
    startvm
    start_clip_serv
    ssh -p 3022 ${1}@127.0.0.1
}

# Main
case $1 in
    '')
        enter_ssh pugachag
        ;;
    enter)
        enter_ssh $2
        ;;
    configure)
        setup
        ;;
esac
